### ISSUE TITLE
Replacing shared secret?

### ISSUE THREAD

**Issue by bentterp** [openxpki/clca#15]
If key is shared 3 of 5 and 3 shareholders are present, is it then possible to redo the sharing without changing the key?

Some way to remove old shareholders and introduce new ones seems needed for long-lasting keys like a CA root key with 20 year lifespan.

**Comment by mbartosch** [comment]
Yes, this is possible. I committed a description and sample script how the share set can be reconstructed, reencrypting the old key with a new secret sharing passphrase.

**Comment by bentterp** [comment]
Awesome! Thanks a bundle, really good to know how to replace the quorum when somebody leaves the company or things like this.
