### ISSUE TITLE
startdate and enddate do not work with initialize

### ISSUE THREAD

**Issue by ksyblast** [openxpki/clca#16]
steps to reproduce:
clca latest version, default config, generate key and run ../bin/clca initialize --startdate 210809 --enddate 410809
error:
`/bin/mv: cannot stat '/home/user/clca/testca1/certs/61A894CA414F7CD6137310F05109C1E12B4D80DB.pem': No such file or directory
Can't open /home/user/clca/testca1/ca/cacert.pem for reading, No such file or directory
139736122066752:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/home/user/clca/testca1/ca/cacert.pem','r')
139736122066752:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load certificate
Could not convert certificate to DER (should not happen).
CA root certificate contents:
Can't open /home/user/clca/testca1/ca/cacert.pem for reading, No such file or directory
139682468243264:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/home/user/clca/testca1/ca/cacert.pem','r')
139682468243264:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load certificate
`
Seems that version 1.11 is not affected

**Comment by ksyblast** [comment]
P.S. it is only reproduced with RANDOMIZE_SERIAL=1

**Comment by mbartosch** [comment]
fixed in f501d98
