### ISSUE TITLE
Issue with PR7 

### ISSUE THREAD

**Issue by DocCyblade** [openxpki/clca#9]
You may want to reverse pull PR7 (https://github.com/openxpki/clca/pull/7) I say this because I was experimenting more with the build and with out the `xterm&` it does not show a window on first boot. I think it is because I was using a persistent drive. For some reason the two builds I have are showing double windows, but I just built another with out the `xterm &` and I get no window. 

I'll keep working on it and track down the cause of the double window. I'll report back on this thread. I'll issue another PR to put xterm back if you want, or you can change it back your self. Just let me know. 

-Ken

**Comment by DocCyblade** [comment]
Doing some testing now. I will update this post with results, and reply with my findings.

This is what I am going to test with:

- HP t610 thin client, 4GB RAM
- Tests 1-3 two LACIE 16GB USB Flash Drive
- Test 4-5 Kingston G2 128GB USB Flash Drive

### Test Set A
- [ ] Build Master branch with jessie with `xterm &` back in the file `package/debian-live/addons.d/10-gui.sh`
   - [ ] Put ISO to 16GB thumb drive
   - [ ] Create 1GB persistence image on vfat partition on other 16GB drive
   - [ ] Test1a: boot without blank persistence drive
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window
   - [ ] Test2a: boot WITH blank persistence drive
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window
   - [ ] Test3a: boot again with persistence drive (2nd boot)
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window
   - [ ] Put ISO to 128GB thumb drive
   - [ ] Create 1GB persistence image on same 128GB thumb drive
   - [ ] Test4a: boot drive once
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window
   - [ ] Test5a: boot drive twice
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window

### Test Set B
- [ ] Build Master branch with jessie without `xterm &`
   - [ ] Put ISO to 16GB thumb drive
   - [ ] Create 1GB persistence image on vfat partition on other 16GB drive
   - [ ] Test1b: boot without blank persistence drive
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window
   - [ ] Test2b: boot WITH blank persistence drive
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window
   - [ ] Test3b: boot again with persistence drive (2nd boot)
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window
   - [ ] Put ISO to 128GB thumb drive
   - [ ] Create 1GB persistence image on same 128GB thumb drive
   - [ ] Test4b: boot drive once
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window
   - [ ] Test5b: boot drive twice
      - [ ] Yes - Two xterm windows
      - [ ] No - One xterm window

**Comment by DocCyblade** [comment]
So it seems I get two xterm windows when logging in using the original script. When using the patch version, I get no xterm window, going to take a good look into the build scripts to see where it may be duplicating.

**Comment by DocCyblade** [comment]
After more review of the file https://github.com/openxpki/clca/blob/master/package/debian-live/addons.d/10-gui.sh it seems the issue is here:

the autostart gets created here for system wide use: (https://github.com/openxpki/clca/blob/master/package/debian-live/addons.d/10-gui.sh#L10) 

Then we are creating script on login, that looks for the open box config dir in the home folder for the user, if it does not exist create it and COPY the auto start system file to the user. This is where we are getting two xterm windows, one in the system autostart and another in the user config (because it was copied from the system, prob for persistence reasoning. 

I purpose, we refactor the gui script to instead of copying the autostart from the system to make the system one smart enough to load background and other things from the current users home (~/) instead of hard coding to /home/user. If we wanted we could detect if there is no autostart file we could create one from a template so there is one there for a persistent drive.

I'll work on this purposed change and submit a PR for review. 

-Ken

**Comment by mbartosch** [comment]
Brilliant, thanks for taking the time to analyze this. I admit I had noticed the double xterm issue some time ago but frankly I really did not care that I had two terminals on the screen.
Looking forward to your PR.

**Comment by DocCyblade** [comment]
I have submitted a pull request PR#10 that fixes the original issue, and fixes the no xterm window.

**Comment by DocCyblade** [comment]
Since PR#10 was merged this can be closed
